export const categories = [
    "Animals That Hop or Jump",
    "Animals That Live Underground",
    "Arctic Animals",
    "Birds",
    "Cat Breeds",
    "Dangerous Animals",
    "Dog Breeds",
    "Farm Animals",
    "Fast Animals",
    "Fish",
    "Mammals",
    "Pets",
    "Reptiles",
    "Slow Animals",
    "Colors",
    "Famous Artists",
    "Famous Paintings",
    "Art Equipment",
    "Art Terms",
    "Types of Art",
    "Medical Terms",
    "Diseases",
    "Medicine Names",
    "Legal Terms",
    "Office Items",
    "Teaching Terms",
    "Areas of Study",
    "Men's Clothing Items",
    "Women's Clothing Items",
    "Styles of Shoes",
    "Cooking Shows",
    "Nickelodeon TV Shows",
    "Prime Time TV Shows",
    "Reality TV Shows",
    "Sit Coms",
    "Cartoon Characters",
    "Actors",
    "Actresses",
    "Blockbusters",
    "Classic Movies",
    "Comedy Movies",
    "Disney Movies",
    "Horror Movies",
    "Science Fiction Movies",
    "Sports Team Names",
    "Sports Terms",
    "Famous Athletes",
    "Sports Played Outside",
    "Sports Played Inside",
    "Olympic Events",
    "Water Sports",
    "Alcoholic Drinks",
    "Beer Brands",
    "Clothing Brands / Designers",
    "Netflix Original TV Shows / Movies",
    "Documentaries",
    "Four-Letter Words",
    "Internal Organs",
    "Things That expand",
    "Cold Drinks",
    "Hot Drinks",
    "Breakfast Foods",
    "Candy Types",
    "Dairy Products",
    "Desserts",
    "Fast Food Items",
    "Ice Cream Flavors",
    "Sandwiches",
    "Herbs & Spices",
    "Flowers",
    "Vegetables",
    "Types of Trees",
    "African Countries",
    "Asian Cities",
    "Countries",
    "European Cities",
    "European Countries",
    "Lakes",
    "Mountain Ranges",
    "Oceans",
    "Rivers",
    "South American Countries",
    "United States Capitals",
    "Dictators",
    "Presidents",
    "Holiday Songs",
    "Holidays",
    "Bathroom Accessories",
    "Kitchen Appliances",
    "Authors",
    "Famous Literary Characters",
    "Novels",
    "Math Terms",
    "Units of Measurement",
    "Bands with One-Word Names",
    "Boy Bands",
    "Children's Songs",
    "Classical Music Composers",
    "Eighties Recording Artists",
    "Female Singers",
    "Love Songs",
    "Male Singers",
    "Wines",
    "Religious Terms",
    "Languages",
    "Museums",
    "Computer Terms",
    "Colleges / Universities",
    "Plays / Musicals",
    "Weather Terms",
    "Words That End with Y",
    "Chain Restaurants",
    "Dance Songs",
    "Stores Found in a Mall",
    "Karaoke Songs",
    "Musical Instruments",
    "Nineties Musical Artists",
    "Rappers",
    "Seventies Musical Artists",
    "Sixties Musical Artists",
    "Songs with a Name in the Title",
    "Elements on the Periodic Table",
    "Chemicals",
    "Bones",
    "Types of Rocks",
    "Insects / Bugs",
    "Apps",
    "Video Games",
    "Websites",
    "Things That Are Cold",
    "Things That Are Flat",
    "Things Found in a Park",
    "Things That Are Made of Glass",
    "Things That Are Made of Plastic",
    "Things That Are Made of Wood",
    "Things That Are Round",
    "Things That Are Sticky",
    "Things That Are Square",
    "Things That Are Terrifying",
    "Things That Burn",
    "Things That Cost a Lot ",
    "Things That Have Spots",
    "Things That Have Stripes",
    "Things That Have Wheels",
    "Things That Smell Bad",
    "Things That Smell Good",
    "Board Games",
    "Types of Toys",
    "Car Models",
    "Insults",
    "Card Games",
    "Modes of Transportation",
    "Beatles Songs",
];
